feat :additional tests
adm-metaex/mplx-staking pull request #33
Opened 2024-09-10 11:11 UTC by RequescoS

2024-09-25 11:01 UTC, StanChe approved these changes
💪

2024-10-03 12:06 UTC, kstepanovdev commented on programs/mpl-staking/tests/test_claim.rs
> -        .assert_on_chain_err(MplStakingError::TokenflowRestricted);
afaik claiming will return errors from the `Staking`. i guess `rewards` even doesn't have such errors.

2024-10-03 12:06 UTC, kstepanovdev commented on programs/mpl-staking/tests/test_claim.rs
> +        .expect_err("Claiming is restricted by Rewards program");
Is it? Probably, the `staking` itself should return errors.

2024-10-03 12:08 UTC, kstepanovdev requested changes
Awesome changes. However, we might want to catch specific errors instead of capturing some errors that occurred in general if it's possible.

2024-10-03 12:23 UTC, kstepanovdev approved these changes
LGTM. Thank you for the refactoring.

2024-10-03 12:24 UTC, merged